version: '3.8'

services:
  redis:
    image: redis:7.0.4
    container_name: slips-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  slips:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slips
    platform: linux/amd64  # For MacOS compatibility
    ports:
      - "55000:55000"  # Web interface port
    environment:
      - TZ=UTC
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NVIDIA_VISIBLE_DEVICES=all  # Enable all NVIDIA GPUs
    volumes:
      - ./dataset:/StratosphereLinuxIPS/dataset  # For PCAP files
      - ./output:/StratosphereLinuxIPS/output    # For output files
    deploy:
      resources:
        limits:
          cpus: '0.7'  # 70% of CPU
          memory: 8G
        reservations:
          memory: 4G
      placement:
        constraints:
          - "node.labels.gpu==true"  # Only run on nodes with GPU
    cap_add:
      - NET_ADMIN  # Required for network monitoring
    network_mode: host  # For Linux/Windows hosts
    depends_on:
      - redis
    runtime: nvidia  # Use NVIDIA runtime
    devices:
      - /dev/nvidia0:/dev/nvidia0  # Mount NVIDIA device
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset

volumes:
  redis_data:
    driver: local